### ISSUE TITLE
Billing request types doesn't match documentation

### ISSUE THREAD

**Issue by brettwillis** [gocardless/gocardless-nodejs#116]
Both `BillingRequestMandateRequest` and `BillingRequestPaymentRequest` are declared twice, and TypeScript merges the declarations. The second declaration includes non-optional fields which seem optional based on the documentation for example:

### `BillingRequestMandateRequest`

The second declaration includes required fields `links` and `verify` fields, where as per the [API documentation](https://developer.gocardless.com/getting-started/billing-requests/creating-a-dd-mandate/#create-a-billing-request), only `curreny` is required:

> ``` POST /billing_requests
> {
>  "billing_requests": {
>    "mandate_request": {
>      "currency": "GBP"
>    }
>  }
>}
>```

https://github.com/gocardless/gocardless-nodejs/blob/97b1d164f431d18528e197ae6d10021b01ea5eb0/src/types/Types.ts#L147-L156

https://github.com/gocardless/gocardless-nodejs/blob/97b1d164f431d18528e197ae6d10021b01ea5eb0/src/types/Types.ts#L368-L395

### `BillingRequestPaymentRequest`

It's a similar story for `BillingRequestPaymentRequest`, declared twice with the second declaration requiring fields that should be optional, please check.

**Comment by afenton90** [comment]
I'm also encountering this issue when trying to setup a billing request. Happy to put in a PR to resolve these.

**Comment by szastupov** [comment]
Hi @brettwillis, @afenton90 👋 

Thanks for reporting the issue. Just want to let you know that we are working on a solution.

**Comment by brettwillis** [comment]
@szastupov Thank you for this. However it seems like the `links`, `metadata`, and `verify` fields are still **_required_** by the typings, where they should be **_optional_** according to the documentation and the API?

**Comment by szastupov** [comment]
@brettwillis we are working on fixing required/optional typing as well 😉
