### ISSUE TITLE
Can't import * as gocardless from 'gocardless-nodejs';

### ISSUE THREAD

**Issue by matteusbarbosa** [gocardless/gocardless-nodejs#154]
Hi guys, anyone have any idea why i cant import gocardless? 

m using new ES6 syntax from NestJS:

`import * as gocardless from 'gocardless-nodejs';`

But it results in:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/6011778/219769879-b1e806f8-a1a0-447f-9ad7-2bde120e9490.png">

@jjholmes927 any ideas?

**Comment by matteusbarbosa** [comment]
### Found solution for NestJS / ES6 thanks to [@mauricedoepke](https://github.com/mauricedoepke)

`import { GoCardlessClient } from 'gocardless-nodejs/client';`

and instead of calling gocardless(...), instance the client:

```
    return new GoCardlessClient(
      process.env.GC_ACCESS_TOKEN,
      constants.Environments.Sandbox,
    );
```

**Comment by jjholmes927** [comment]
Awesome, Glad you got it resolved! I'll close this @matteusbarbosa 👍
