### ISSUE TITLE
Make prefilled_customer properties optional

### ISSUE THREAD

**Issue by RomainCscnLF** [gocardless/gocardless-nodejs#64]
Hi! We're using your library and would like to use the `prefilled_customer` property when creating a redirectFlows (using `client.redirectFlows.create`).

We are using TypeScript and we can't use `prefilled_customer` without putting all the property with empty string for the one we don't want to fill. 

For example if we omit `region`:
```
Property 'region' is missing in type '{ 
  address_line2: string; 
  address_line3: string; 
  ... 10 more ... ; 
  country_code: string; 
}'
but required in type 'RedirectFlowPrefilledCustomer'.
```

**Comment by tallosan** [comment]
Hey @RomainCscnLF, thanks for the report!

We'll be rolling out a fix for this in the next few days.
