### ISSUE TITLE
Impossible to generate mandate pdf in other language

### ISSUE THREAD

**Issue by RomainCscnLF** [gocardless/gocardless-nodejs#66]
It does not seem possible to generate mandate PDF in other language. 

https://developer.gocardless.com/api-reference/#mandate-pdfs-create-a-mandate-pdf

In Python, it is possible to do the following:
```python
client.mandate_pdfs.create(params={
  "iban": "FR14BARC20000055779911"
}, headers={
  "Accept-Language": "fr"
})
```
Is there any possibility to do this with this library?

**Comment by tallosan** [comment]
Thanks for the report! We'll have a fix out for this in the next few days.

**Comment by RomainCscnLF** [comment]
Hi! 

Could you update the related docs also? https://developer.gocardless.com/api-reference/#helper-endpoints-mandate-pdfs

Thanks.

**Comment by tallosan** [comment]
Yeah, good shout! We've recently updated the docs, so the most recent version should be available shortly.

**Comment by RomainCscnLF** [comment]
Are you sure that this is actually working? I tried this but I had to put an empty string as a second parameter for the `idempotencyKey`. Plus I think you put `Accept-Header` where It should be `Accept-Language`.

```javascript
await client.mandatePdfs.create(
  {
    account_number: "44779911",
    branch_code: "200000",
    country_code: "GB"
  },
  { customHeaders: { "Accept-Header": "fr" } }
);
```

**Comment by tallosan** [comment]
Ahh, yes you're correct. Pretty careless mistake on my part, so apologies for that. I'll get this fixed up ASAP.

**Comment by RomainCscnLF** [comment]
You're welcome! Thanks for the reactivity.
