### ISSUE TITLE
Api.isIdempotencyConflict error when hosting package in Firebase Cloud Function

### ISSUE THREAD

**Issue by alfie-ab** [gocardless/gocardless-nodejs#69]
Hi! I'm using firebase cloud functions to host the client and I have this simple boilerplate code set up to add a customer:

```
import * as functions from 'firebase-functions';
const gocardless = require('gocardless-nodejs');
const constants = require('gocardless-nodejs/constants');
import { config } from '../goCardless/config';

const goCardless = gocardless(config.token, constants.Environments.Sandbox);

export const getPaymentUrl = functions.https.onCall(
  async (session_token, success_redirect_url) => {
    try {
      const redirectFlow = await goCardless.redirectFlows.create({
        description: 'Collective',
        session_token,
        success_redirect_url
      });
      return redirectFlow;
    } catch (error) {
      console.log(error);
    }
  }
);
```

When I call `getPaymentUrl` in a local shell of firebase functions, it all works. And when I run it in a simple node/express server it also works.

However when I deploy the function to firebase I get this error:

```
TypeError: Cannot read property 'statusCode' of undefined     
at Api.isIdempotencyConflict (/workspace/node_modules/gocardless-nodejs/api/api.js:126:26)     at Api.request (/workspace/node_modules/gocardless-nodejs/api/api.js:58:22)    
at process._tickCallback (internal/process/next_tick.js:68:7) | more_vert
``` 

I think the error being displayed is likely hiding the actual error?

Versions: 
firebase-functions: 3.6.0
gocardless-nodejs: 1.1.1
node: 10

Thanks, and let me know if you need any more info!

**Comment by lancscoder** [comment]
Hi @alfie-ab 

We've just pushed version `1.1.2` to npm, this should show more details about the error rather than the: 
```
TypeError: Cannot read property 'statusCode' of undefined     
at Api.isIdempotencyConflict (/workspace/node_modules/gocardless-nodejs/api/api.js:126:26)     at Api.request (/workspace/node_modules/gocardless-nodejs/api/api.js:58:22)    
at process._tickCallback (internal/process/next_tick.js:68:7) | more_vert
```

**Comment by alfie-ab** [comment]
Amazing, so v1.1.2 revealed the actual error in the firebase logs which was that since we're on the free plan firebase was blocking calls to external services. Have now upgraded and works perfectly!

Thanks so much for the quick turnaround and especially @isaacseymour for answering all my questions. Am closing the issue :)
