### ISSUE TITLE
Use GitHub release and changelog

### ISSUE THREAD

**Issue by RomainCscnLF** [gocardless/gocardless-nodejs#71]
Hello,

It is sometimes hard to know what was shipped during the previous releases and I think it would be great if you could put a changelog in GitHub releases.

For example, I had to find the related PR for the `1.1.2` version to know what it was about.

**Comment by lancscoder** [comment]
Hi @RomainCscnLF,

You are right we should be using GitHub Release and changelogs (we do on our other libraries).

We will put in place procedures to make sure we keep this up to date going forward.

Thanks for bringing this to our attention.

**Comment by RomainCscnLF** [comment]
Hi @lancscoder, 

Thanks for your quick reply 🚀  

Happy to hear that! I can close this issue then 💯
