### ISSUE TITLE
'links' property is not optional in RedirectFlowCreateRequest

### ISSUE THREAD

**Issue by JimAllanson** [gocardless/gocardless-nodejs#82]
According to the [API reference](https://developer.gocardless.com/api-reference/#redirect-flows-create-a-redirect-flow) the links property is optional, and is only needed when an account has multiple creditors. The REST API appears to work fine when this parameter is omitted.

In the RedirectFlowCreateRequest interface below, this property is not marked as optional.
https://github.com/gocardless/gocardless-nodejs/blob/c6cdd4a069bd08f1bf5cb44b0726a6db8c7a002f/src/services/redirectFlowService.ts#L20

It looks like the code here might be generated / imported from elsewhere, so I'm assuming I shouldn't open a pull request?

**Comment by tallosan** [comment]
Hi @JimAllanson,

This should now be fixed in the latest version (`1.4.1`).
