### ISSUE TITLE
Update crypto-js dependency

### ISSUE THREAD

**Issue by wpf500** [gocardless/gocardless-nodejs#86]
Hi, can you upgrade your version of `crypto-js` to `4.0.0`? Snyk is [reporting a vulnerability](https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472) when I include `gocardless-nodejs` in my project. I believe the only change to `crypto-js` is to use native randomness generators that won't work in IE 10 or React Native, so it should be fine for a NodeJS library.

**Comment by szastupov** [comment]
Thank you for reporting it and sorry for the lack of activity. This has been fixed in #122
