### ISSUE TITLE
Cloud functions GotError

### ISSUE THREAD

**Issue by hhochart29** [gocardless/gocardless-nodejs#88]
Hi,

while using the gocardless nodejs api in a firebase cloud functions, i have this specific error while creating a paymentFlow

```
{"severity":"ERROR","message":"Unhandled error GotError: connect ECONNREFUSED 127.0.0.1:443\n    at onError (/Users/herve/dev/xxxxxxx/functions/node_modules/got/dist/source/request-as-event-emitter.js:140:29)\n    at handleRequest (/Users/herve/dev/xxxxxxxx/functions/node_modules/got/dist/source/request-as-event-emitter.js:173:17)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {\n  name: 'RequestError',\n  code: 'ECONNREFUSED'\n}"}
```

Do you have any ideas on what could cause this ?
It seem to be related to got 

Edit: The error seem to be coming from the mailjet library. There must be some conflic with the `http-proxy-agent` dependency

**Comment by laurie-wrisk** [comment]
@hhochart29 Did you ever find a solution to this, I'm seeing exactly the same thing
