### ISSUE TITLE
Rate limit headers

### ISSUE THREAD

**Issue by aharin** [gocardless/gocardless-nodejs#89]
Is there any way to access ratelimit-remaining and ratelimit-reset headers when api call throws  a rate_limit_exceeded error?

**Comment by danwakefield** [comment]
Hi, thanks for pointing out we are missing this ability.
We have made a change so that the response object is now included in the exception.
This should allow you to [access the headers you need.](https://developer.gocardless.com/api-reference/#making-requests-rate-limiting)

This will be in v1.4.3
