### ISSUE TITLE
TypeError: Cannot read property 'payments' of undefined on idempotency key violation

### ISSUE THREAD

**Issue by aharin** [gocardless/gocardless-nodejs#91]
Incorrect exception is thrown by the library when idempotency key is violated. It seems like it attampts to parse error response as successful and fails since error response does not contain 'payments' attribute.

**Comment by aharin** [comment]
This is happening when creating a Payment and raiseOnIdempotencyConflict is set to false. I have an existing failed payment with the same Idempotency key. Looks like the library is meant to return existing payment in this case. However I am getting TypeError instead.

**Comment by danwakefield** [comment]
This should be fixed in the latest release https://github.com/gocardless/gocardless-nodejs/releases/tag/v2.1.0
